# Generated by Django 5.2 on 2025-04-18 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_api', '0002_tourpackage_tourbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='excluded_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='included_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
