# Generated by Django 5.2 on 2025-04-18 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_api', '0003_tourpackage_capacity_tourpackage_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
