# Generated by Django 5.2 on 2025-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_api', '0004_alter_tourpackage_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='last_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
