# Generated by Django 5.2 on 2025-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_api', '0005_tourpackage_last_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='last_booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
