# Generated by Django 5.2 on 2025-04-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_api', '0007_tourbooking_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='tracking_id',
            field=models.UUIDField(editable=False),
        ),
    ]
